[package]
name = "nova-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
# ! Nova dependencies
nova-snark = { git = "https://github.com/MVPWorkshop/Nova", branch = "no_std", default-features = false }
ff = "*"
postcard = { version = "*", default-features = false, features = ["alloc"] }
thiserror = { version = "*", default-features = false }
pasta_curves = "*"

[dev-dependencies]
serde_json = "*"

[features]
default = ["std"]
std = []
