[package]
name = "nova-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
# ! Nova dependencies
nova-snark = { git = "https://github.com/MVPWorkshop/Nova", default-features = false }
ff = "*"
serde_json = "*"
postcard = { version = "*", default-features = false, features = ["alloc"] }
thiserror = "*"
pasta_curves = "*"
